<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class MasterApplicationSettingDetailResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'master_application_setting_id' => $this->mas_app_stng_id,
            'language_id' => $this->language_id,
            'page_title' => $this->page_title,
            'description' => $this->description,
            'school_lable' => $this->school_lable,
            'school_placeholder' => $this->school_placeholder,
            'school_error' => $this->school_error,
            'first_name_label' => $this->first_name_label,
            'first_name_placeholder' => $this->first_name_placeholder,
            'first_name_error' => $this->first_name_error,
            'last_name_label' => $this->last_name_label,
            'last_name_placeholder' => $this->last_name_placeholder,
            'last_name_error' => $this->last_name_error,
            'email_label' => $this->email_label,
            'email_placeholder' => $this->email_placeholder,
            'email_error' => $this->email_error,
            'confirm_email_label' => $this->confirm_email_label,
            'confirm_email_placeholder' => $this->confirm_email_placeholder,
            'confirm_email_error' => $this->confirm_email_error,
            'dob_label' => $this->dob_label,
            'dob_placeholder' => $this->dob_placeholder,
            'dob_error' => $this->dob_error,
            'button_text' => $this->button_text,
            'gender_label' => $this->gender_label,
            'gender_placeholder' => $this->gender_placeholder,
            'gender_error' => $this->gender_error,
            'phone_label' => $this->phone_label,
            'phone_placeholder' => $this->phone_placeholder,
            'phone_error' => $this->phone_error,
            'can_school_text_label' => $this->can_school_text_label,
            'can_school_text_placeholder' => $this->can_school_text_placeholder,
            'can_school_text_error' => $this->can_school_text_error,
            'message_app_label' => $this->message_app_label,
            'message_app_placeholder' => $this->message_app_placeholder,
            'message_app_error' => $this->message_app_error,
            'currently_study_label' => $this->currently_study_label,
            'currently_study_placeholder' => $this->currently_study_placeholder,
            'currently_study_error' => $this->currently_study_error,
            'country_citzenship_label' => $this->country_citzenship_label,
            'country_citzenship_placeholder' => $this->country_citzenship_placeholder,
            'country_citzenship_error' => $this->country_citzenship_error,
            'live_in_country_citzenship_label' => $this->live_in_country_citzenship_label,
            'live_in_country_citzenship_placeholder' => $this->live_in_country_citzenship_placeholder,
            'live_in_country_citzenship_error' => $this->live_in_country_citzenship_error,
            'current_residence_label' => $this->current_residence_label,
            'current_residence_placeholder' => $this->current_residence_placeholder,
            'current_residence_error' => $this->current_residence_error,
            'country_residence_status_label' => $this->country_residence_status_label,
            'country_residence_status_placeholder' => $this->country_residence_status_placeholder,
            'country_residence_status_error' => $this->country_residence_status_error,
            'mailing_address_label' => $this->mailing_address_label,
            'mailing_address_placeholder' => $this->mailing_address_placeholder,
            'mailing_address_error' => $this->mailing_address_error,
            'high_school_name_label' => $this->high_school_name_label,
            'high_school_name_placeholder' => $this->high_school_name_placeholder,
            'high_school_name_error' => $this->high_school_name_error,
            'letter_of_intent_label' => $this->letter_of_intent_label,
            'letter_of_intent_placeholder' => $this->letter_of_intent_placeholder,
            'letter_of_intent_error' => $this->letter_of_intent_error,
            'statement_of_purpose_label' => $this->statement_of_purpose_label,
            'statement_of_purpose_placeholder' => $this->statement_of_purpose_placeholder,
            'statement_of_purpose_error' => $this->statement_of_purpose_error,
            'when_plan_to_start_label' => $this->when_plan_to_start_label,
            'when_plan_to_start_placeholder' => $this->when_plan_to_start_placeholder,
            'when_plan_to_start_error' => $this->when_plan_to_start_error,
            'intrested_in_label' => $this->intrested_in_label,
            'intrested_in_placeholder' => $this->intrested_in_placeholder,
            'intrested_in_error' => $this->intrested_in_error,
            'would_like_to_study_label' => $this->would_like_to_study_label,
            'would_like_to_study_placeholder' => $this->would_like_to_study_placeholder,
            'would_like_to_study_error' => $this->would_like_to_study_error,
            'tuition_funding_source_label' => $this->tuition_funding_source_label,
            'tuition_funding_source_placeholder' => $this->tuition_funding_source_placeholder,
            'tuition_funding_source_error' => $this->tuition_funding_source_error,
            'test_taken_label' => $this->test_taken_label,
            'test_taken_placeholder' => $this->test_taken_placeholder,
            'test_taken_error' => $this->test_taken_error,
            'additional_label' => $this->additional_label,
            'additional_placeholder' => $this->additional_placeholder,
            'additional_error' => $this->additional_error,
            'add_something_lable' => $this->add_something_lable,
            'add_something_placeholder' => $this->add_something_placeholder,
            'add_something_error' => $this->add_something_error,
            'currently_live_in_lable' => $this->currently_live_in_lable,
            'currently_live_in_placeholder' => $this->currently_live_in_placeholder,
            'currently_live_in_error' => $this->currently_live_in_error,
            'study_permet_lable' => $this->study_permet_lable,
            'study_permet_placeholder' => $this->study_permet_placeholder,
            'study_permet_error' => $this->study_permet_error,
            'send_copy_lable' => $this->send_copy_lable,
            'send_copy_placeholder' => $this->send_copy_placeholder,
            'send_copy_error' => $this->send_copy_error,
            'where_want_to_study_lable' => $this->where_want_to_study_lable,
            'where_want_to_study_placeholder' => $this->where_want_to_study_placeholder,
            'where_want_to_study_error' => $this->where_want_to_study_error,
            'high_school_city_lable' => $this->high_school_city_lable,
            'high_school_city_placeholder' => $this->high_school_city_placeholder,
            'high_school_city_error' => $this->high_school_city_error,
            'high_school_country_lable' => $this->high_school_country_lable,
            'high_school_country_placeholder' => $this->high_school_country_placeholder,
            'high_school_country_error' => $this->high_school_country_error,
            'high_school_cgpa_lable' => $this->high_school_cgpa_lable,
            'high_school_cgpa_placeholder' => $this->high_school_cgpa_placeholder,
            'high_school_cgpa_error' => $this->high_school_cgpa_error,
            'student_type_lable' => $this->student_type_lable,
            'student_type_placeholder' => $this->student_type_placeholder,
            'student_type_error' => $this->student_type_error,
            'privacy_policy' => $this->privacy_policy,
            'message_app_username_label' => $this->message_app_username_label,
            'message_app_username_placeholder' => $this->message_app_username_placeholder,
            'message_app_username_error' => $this->message_app_username_error,
            'master_application_setting' => new MasterApplicationSettingResource($this->whenLoaded('masterApplicationSetting')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
