<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class RegisterBusinessDetailResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'page_title' => $this->page_title,
            'package_section_title' => $this->package_section_title,
            'business_category_text' => $this->business_category_text,
            'business_category_1_lable' => $this->business_category_1_lable,
            'business_category_1_placeholder' => $this->business_category_1_placeholder,
            'business_category_1_error' => $this->business_category_1_error,
            'business_category_2_lable' => $this->business_category_2_lable,
            'business_category_2_placeholder' => $this->business_category_2_placeholder,
            'business_category_2_error' => $this->business_category_2_error,
            'business_category_3_lable' => $this->business_category_3_lable,
            'business_category_3_placeholder' => $this->business_category_3_placeholder,
            'business_category_3_error' => $this->business_category_3_error,
            'description_lable' => $this->description_lable,
            'description_placeholder' => $this->description_placeholder,
            'description_error' => $this->description_error,
            'detail_description_lable' => $this->detail_description_lable,
            'detail_description_placeholder' => $this->detail_description_placeholder,
            'detail_description_error' => $this->detail_description_error,
            'name_lable' => $this->name_lable,
            'name_placeholder' => $this->name_placeholder,
            'name_error' => $this->name_error,
            'welcome_video_label' => $this->welcome_video_label,
            'welcome_video_placeholder' => $this->welcome_video_placeholder,
            'welcome_video_error' => $this->welcome_video_error,
            'keywords_label' => $this->keywords_label,
            'keywords_placeholder' => $this->keywords_placeholder,
            'keywords_error' => $this->keywords_error,
            'password_label' => $this->password_label,
            'password_placeholder' => $this->password_placeholder,
            'password_error' => $this->password_error,
            'confirm_password_label' => $this->confirm_password_label,
            'confirm_password_placeholder' => $this->confirm_password_placeholder,
            'confirm_password_error' => $this->confirm_password_error,
            'website_url_lable' => $this->website_url_lable,
            'website_url_placeholder' => $this->website_url_placeholder,
            'website_url_error' => $this->website_url_error,
            'contact_lable' => $this->contact_lable,
            'contact_placeholder' => $this->contact_placeholder,
            'contact_error' => $this->contact_error,
            'email_lable' => $this->email_lable,
            'email_placeholder' => $this->email_placeholder,
            'email_error' => $this->email_error,
            'phone_lable' => $this->phone_lable,
            'phone_placeholder' => $this->phone_placeholder,
            'phone_error' => $this->phone_error,
            'address_lable' => $this->address_lable,
            'address_placeholder' => $this->address_placeholder,
            'address_error' => $this->address_error,
            'logo_lable' => $this->logo_lable,
            'logo_placeholder' => $this->logo_placeholder,
            'logo_error' => $this->logo_error,
            'media_title' => $this->media_title,
            'media_title_label' => $this->media_title_label,
            'media_title_placeholder' => $this->media_title_placeholder,
            'media_title_error' => $this->media_title_error,
            'media_description_label' => $this->media_description_label,
            'media_description_placeholder' => $this->media_description_placeholder,
            'media_description_error' => $this->media_description_error,
            'file_lable' => $this->file_lable,
            'file_placeholder' => $this->file_placeholder,
            'file_error' => $this->file_error,
            'facebook_lable' => $this->facebook_lable,
            'facebook_placeholder' => $this->facebook_placeholder,
            'facebook_error' => $this->facebook_error,
            'twitter_lable' => $this->twitter_lable,
            'twitter_placeholder' => $this->twitter_placeholder,
            'twitter_error' => $this->twitter_error,
            'youtube_lable' => $this->youtube_lable,
            'youtube_placeholder' => $this->youtube_placeholder,
            'youtube_error' => $this->youtube_error,
            'linkedin_lable' => $this->linkedin_lable,
            'linkedin_placeholder' => $this->linkedin_placeholder,
            'linkedin_error' => $this->linkedin_error,
            'privacy_text_1' => $this->privacy_text_1,
            'privacy_text_2' => $this->privacy_text_2,
            'proceed_button_text' => $this->proceed_button_text,
            'social_media_title' => $this->social_media_title,
            'language_id' => $this->language_id,
            'social_media_heading_text' => $this->social_media_heading_text,
            'media_heading_text' => $this->media_heading_text,
            'business_category_heading_text' => $this->business_category_heading_text,
            'business_profile_heading_text' => $this->business_profile_heading_text,
            'registration_package_heading_text' => $this->registration_package_heading_text,
            'register_business_setting' => new RegisterBusinessResource($this->whenLoaded('registerBusiness')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
